services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $pluginDirectory: "%kimai.plugin_dir%"
            $dataDirectory: "%kimai.data_dir%"

    KimaiPlugin\ChromeExtBundle\:
        resource: '../../*'
        exclude: '../../{Resources}'

    KimaiPlugin\ChromeExtBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
        public: true
                
    KimaiPlugin\ChromeExtBundle\Repository\ExtProjectRepository:
        class:     Doctrine\ORM\EntityRepository
        factory:   ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['KimaiPlugin\ChromeExtBundle\Entity\ExtProject']
        